"use client";
// simport "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { createContext, useContext, useEffect, useState } from "react";
// import { getData } from "../../function";
export const Searchh = createContext();

export const useSearch = () => useContext(Searchh);


// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [Value, setValue] = useState("");

  const [blogs, setBlogs] = useState([]);
  const [pages, setPages] = useState(1);

  useEffect(() => {
    const getBlogs = async () => {
      const data = await getData(`https://dev.to/api/articles?page=${pages}`);
      setBlogs(data);
    };
    getBlogs();
  }, [pages]);

  return (
    <html lang="en">
      <body className="w-full flex justify-center bg-white">
        <Searchh.Provider value={{Value,setValue,blogs}}>
          <div className="w-[1500px]">
            <Header />
            {children}
            <Footer />
          </div>
        </Searchh.Provider>
      </body>
    </html>
  );
}
